// Code generated by "stringer -type=PacketCode,PacketType -output gen_string.go"; DO NOT EDIT.

package eap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeRequest-1]
	_ = x[CodeResponse-2]
	_ = x[CodeSuccess-3]
	_ = x[CodeFailure-4]
}

const _PacketCode_name = "CodeRequestCodeResponseCodeSuccessCodeFailure"

var _PacketCode_index = [...]uint8{0, 11, 23, 34, 45}

func (i PacketCode) String() string {
	i -= 1
	if i >= PacketCode(len(_PacketCode_index)-1) {
		return "PacketCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PacketCode_name[_PacketCode_index[i]:_PacketCode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeIdentity-1]
	_ = x[TypeTLS-13]
}

const (
	_PacketType_name_0 = "TypeIdentity"
	_PacketType_name_1 = "TypeTLS"
)

func (i PacketType) String() string {
	switch {
	case i == 1:
		return _PacketType_name_0
	case i == 13:
		return _PacketType_name_1
	default:
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
